services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./biblioteca-backend
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/biblioteca
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user123
    volumes:
      - ./biblioteca-backend/uploads:/app/uploads
    networks:
      - app-network

  frontend:
    build: ./biblioteca-frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    networks:
      - app-network
    environment:
      API_URL: http://backend:8080

volumes:
  db_data:

networks:
  app-network:
    driver: bridge